### ISSUE TITLE
White screen after installation

### ISSUE THREAD

**Issue by KaezerR** [basknol/MMM-PushBulletNotifications#1]
Hello @basknol , at first thank you for your work on this module!
But it happens that I encounter a problem, I tried many techniques, but after the addition of your module I get a white screen, your help is welcome!

Thank you

**Comment by basknol** [comment]
Hello @SPECTERR,
The first thing that I can think of: did you go into the MMM-PushBulletNotifications directory and run `npm install`  after cloning the module (MMM-PushBulletNotifications)? Otherwise the dependencies are not loaded and Magic Mirror will not start correctly. A simple way to check this, is to see if there is a node_modules folder in the MMM-PushBulletNotifications folder.

I also just did some bugfixing because notifications were not shown if only an AccessToken was specified as module configuration.

If this does not solve your problem, could you please provide some more information? What did you try to get it working? What does your config looks like?

Hope this helps, please let me know if you get it working.

**Comment by KaezerR** [comment]
Hi @basknol, thanks for your quick reply, i have run the install npm in the MMM-PushBulletNotifications file. There is also the node_modules file. My config file looks like this: 

```
/***************` AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config =
{
        language: "fr",
        modules: [
                {
                        module: "alert",
                        config: {

                        }
                },
                {
                        module: "clock",
                        position: "top_left",
                        config: {

                        }
                },
                {
                        module: "calendar",
                        header: "Calendrier",
                        position: "top_left",
                        config: {
                                calendars: [
                                        {
                                                symbol: "calendar-check-o ",
                                                url: "https://calendar.google.com/xxxxxxxxxxxxxxxxxxxx
                                        },
{
                                                symbol: "calendar-check-o ",
                                                url: "https://outlook.live.com/xxxxxxxxxxxxxxxxxxxxxxxxxxx
                                        }
                                ],
                                titleReplace: {
                                        "De verjaardag van ": "",
                                        "'s birthday": ""
                                }
                        }
                },
                {
                        module: "currentweather",
                        position: "top_right",
                        config: {
                                location: "xxx",
                                appid: "xxxxxxxxxxxxxxxxxxxxxxx",
                                iconTable: {
                                        "01d": "wi-day-sunny",
                                        "02d": "wi-day-cloudy",
                                        "03d": "wi-cloudy",
                                        "04d": "wi-cloudy-windy",
                                        "09d": "wi-showers",
                                        "10d": "wi-rain",
                                        "11d": "wi-thunderstorm",
                                        "13d": "wi-snow",
                                        "50d": "wi-fog",
                                        "01n": "wi-night-clear",
                                        "02n": "wi-night-cloudy",
                                        "03n": "wi-night-cloudy",
                                        "04n": "wi-night-cloudy",
                                        "09n": "wi-night-showers",
                                        "10n": "wi-night-rain",
                                        "11n": "wi-night-thunderstorm",
                                        "13n": "wi-night-snow",
                                        "50n": "wi-night-alt-cloudy-windy"
                                }
                        }
                },
                {
                        module: "weatherforecast",
                        position: "top_right",
                        header: "Prévisions Météorologiques",
                        config: {
                                location: "xxxx",
                                locationID: "xxxxxx",
                                appid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                iconTable: {
                                        "01d": "wi-day-sunny",
                                        "02d": "wi-day-cloudy",
                                        "03n": "wi-night-cloudy",
                                        "04n": "wi-night-cloudy",
                                        "09n": "wi-night-showers",
                                        "10n": "wi-night-rain",
                                        "11n": "wi-night-thunderstorm",
                                        "13n": "wi-night-snow",
                                        "50n": "wi-night-alt-cloudy-windy"
                                }
                        }
                },
                {
                        module: "newsfeed",
                        position: "bottom_bar",
                        header: "",
                        config: {
                                feeds: [
                                        {
                                                title: "Le Monde",
                                                url: "https://www.lemonde.fr/rss/une.xml"
                                        }
                                ]
                        }
                },
                {
                        module: "MMM-Wunderlist-Enhanced",
                        position: "bottom_left",
                        header: "Wunderlist",
                        config: {
                                accessToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                                clientID: "xxxxxxxxxxxxxxxxxxx",
                                lists: [
                                        "inbox",
                                        "House to do"
                                ]
                        }
                },
                {
                        module: "MMM-Remote-Control",
                        config: {

                        }
                },
{
		module: 'MMM-PushBulletNotifications',
		header: 'Notifications',
		position: 'bottom_right',	// This can be any of the regions.		
		config: {
			// See 'Configuration options' for more information.
			accessToken: "xxxxxxxxxxxxxxxxxxxxx", //PushBullet API Access Token
			numberOfNotifications: 3,
			filterTargetDeviceName: "",
			showNotificationsSentToAllDevices: true,
			onlyAllowCommandsFromSourceDevices: [],
			fetchLimitPushBullet: 50,
			showNotificationsOnLoad: true,
			showMessage: true,
			showIcons: true,
			showDateTime: true,
			localesDateTime: 'fr-FR',
			playSoundOnNotificationReceived: true,
			soundFile: 'modules/MMM-PushBulletNotifications/sounds/new-message.mp3',			
			maxMsgCharacters: 50,
			maxHeaderCharacters: 32
		}
	}
        ],
        paths: {
                modules: "modules",
                vendor: "vendor"
        }
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
```

I made a complete backup of my SD card before there is this problem, and when I delete the module it works again.

Thanks for your help !

**Comment by KaezerR** [comment]
But i didn't understand this : 

> I also just did some bugfixing because notifications were not shown if only an AccessToken was specified as module configuration.

**Comment by basknol** [comment]
Hi @SPECTERR,
The config file looks fine to me. What version of the Magic Mirror are you running?
I have developed and tested this module on version 2.3.1. of the Magic Mirror. Today I have added the 'requiresVersion' option to the MMM-PushBulletNotifications module so it will only be loaded when the Magic Mirror version is 2.3.1 or higher.

After you reported this issue I did some testing and discovered that no notifications were shown if I only set an AccessToken in the module configuration and the defaults are used.
```
{
	module: 'MMM-PushBulletNotifications',
	header: 'Notifications',
	position: 'bottom_right',	// This can be any of the regions.		
	config: {
		// See 'Configuration options' for more information.
		accessToken: "xxxxxxxxxxxxxxxxxxxxx", //PushBullet API Access Token
	}
}
```
If have fixed that bug, so you also might want to get the latest version.

Did you look in the logfiles for clues or try to start the Magic Mirror with `npm start dev`? Are there any errors?

Hope this helps, would be nice if this module will also work for you.

**Comment by KaezerR** [comment]
Thank you @basknol for the help you give me, I updated the whole of my RPI system and the MagicMirror (it was almost a year without update), also updated your module, and asleep it appears, seems functional but I do not receive any notification on it! Maybe I have wrongly configured the module but I do not think so, it may be the API?

**Comment by KaezerR** [comment]
In my opinion there is no error with your module with `npm start dev`

```
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Wunderlist-Enhanced
Initializing new module helper ...
Module helper loaded: MMM-PushBulletNotifications
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
All module helpers loaded.
Starting server on port 8080 ...
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Wunderlist-Enhanced
Connecting socket for: MMM-PushBulletNotifications
Connecting socket for: MMM-Remote-Control
Starting node helper for: MMM-Remote-Control
Sockets connected & modules started ...
Whoops! There was an uncaught exception...
{ Error: listen EADDRINUSE 0.0.0.0:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:685:11)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080 }
MagicMirror will not quit, but it might be a good idea to check why this happene                                     d. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://gi                                     thub.com/MichMich/MagicMirror/issues
Launching application.
(node:3953) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec                                     tion id: 1): TypeError: Cannot read property 'refs' of undefined
(node:3953) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre                                     cated. In the future, promise rejections that are not handled will terminate the                                      Node.js process with a non-zero exit code.
(node:3953) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec                                     tion id: 2): TypeError: Cannot read property 'refs' of undefined
(node:3953) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec                                     tion id: 3): TypeError: Cannot read property 'refs' of undefined
(node:3953) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec                                     tion id: 4): TypeError: Cannot read property 'refs' of undefined
(node:3953) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec                                     tion id: 5): TypeError: Cannot read property 'refs' of undefined
^CShutting down server...
Stopping module helper: calendar
Stopping module helper: newsfeed
Stopping module helper: MMM-Wunderlist-Enhanced
Stopping module helper: MMM-PushBulletNotifications
Stopping module helper: MMM-Remote-Control

```

**Comment by basknol** [comment]
Hi @SPECTERR, good to hear you solved the white screen issue by updating to the latest version of Magic Mirror.
The uncaught exception message ('Error: listen EADDRINUSE 0.0.0.0:8080') is probably because the Magic Mirror is already running on port 8080 and then you run another instance using `npm start dev`. 
Do you use [PM2](https://github.com/MichMich/MagicMirror/wiki/Auto-Starting-MagicMirror) to startup the Magic Mirror automatically? Then you can try to first stop the Magic Mirror using `pm2 stop mm` and then run `npm start dev`

Example output `npm start dev`:
```
npm start dev

> magicmirror@2.3.1 start MagicMirror
> sh run-start.sh "dev"


Starting MagicMirror: v2.3.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-ImageFileWatcher
Initializing new module helper ...
Module helper loaded: MMM-PushBulletNotifications
Initializing new module helper ...
Module helper loaded: MMM-TTS
All module helpers loaded.
Starting server on port 8080 ...
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-ImageFileWatcher
Connecting socket for: MMM-PushBulletNotifications
Connecting socket for: MMM-TTS
Starting node helper for: MMM-TTS
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://www.calendarlabs.com/templates/ical/US-Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
Start watching: modules/MMM-ImageFileWatcher/Images
START received
PushBullet connected
```

If the MMM-PushBulletNotifications module is connected to PushBullet you should see: 'PushBullet connected'.

If for example the AccessToken is invalid you should see something like this:
```
START received
Error fetching devices. Error: Access token is missing or invalid.
Push stream error
Error: Server responded with a non-101 status: 401 Unauthorized
Response Headers Follow:
date: Mon, 30 Jul 2018 20:03:11 GMT
content-length: 0
content-type: text/plain; charset=utf-8

    at WebSocketClient.failHandshake (MMM-PushBulletNotifications\node_modules\websocket\lib\WebSocketClient.js:326:32)
    at ClientRequest.<anonymous> (MMM-PushBulletNotifications\node_modules\websocket\lib\WebSocketClient.js:265:18)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:522:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:411:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
```
Or a message: 'Error: API Key is required'.

Let me know if you see an error or the message 'PushBullet connected'. Because if you are connected, there is probably still something wrong in the module.

**Comment by KaezerR** [comment]
Hey @basknol, At the beginning there were still some automatic launch problems I had to improvise a script inserted in `~/.config/lxsession/LXDE-pi/autostart`
 for the automatic launch.

But nevertheless I managed to find something interesting 
```
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Wunderlist-Enhanced
Initializing new module helper ...
Module helper loaded: MMM-PushBulletNotifications
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
All module helpers loaded.
Starting server on port 8080 ...
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Wunderlist-Enhanced
Connecting socket for: MMM-PushBulletNotifications
Connecting socket for: MMM-Remote-Control
Starting node helper for: MMM-Remote-Control
Sockets connected & modules started ...
Launching application.
(node:2011) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'refs' of undefined
(node:2011) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:2011) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'refs' of undefined
(node:2011) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'refs' of undefined
(node:2011) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'refs' of undefined
(node:2011) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'refs' of undefined
(node:2011) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property 'refs' of undefined
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/fr.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxm/public/basic.ics - Interval: 300000
Create new calendar fetcher for url: https://outlook.live.com/owa//calendar/cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx19/calendar.ics - Interval: 300000
Create new news fetcher for url: https://www.lemonde.fr/rss/une.xml - Interval: 300000
START received
Create new todo fetcher for list: inbox - Interval: 60000
PushBullet connected
(node:2011) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: Cannot read property 'body' of undefined
 
```

Issue with node, permission or with the code ? I think this problem does not come from your module, but from the way I put the system in place.

**Comment by basknol** [comment]
Hi @SPECTERR, thanks for testing and providing the results. 
There is a message 'PushBullet connected', so the AccessToken should be ok. 

I am not sure where the 'UnhandledPromiseRejectionWarning' is coming from. Is it possible for you to disable the other (MMM-) modules to see if these warnings still persists? You can add `disabled: true' in the config for a module, see example below:

```
{
    module: "compliments",
    disabled: true,
    position: "lower_third"
},
```

When using `npm start dev`. The Magic Mirror is shown and also the console tab of the browser, this also holds some logging. Do you see errors in there? Or do you see a log with the text 'DEVICES' and 'PUSHES' comming from MMM-PushBulletNotifications.js:160?

What do you see on the mirror? Do you see the 'Notifications' header without notifications under it? Or nothing at all?

**Comment by basknol** [comment]
I think I have a possible cause for the warning message below.

> UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'body' of undefined

I emptied my push history and then saw this warning when starting the mirror using `npm start dev`. I will make a fix for that, but if you have any pushes in PushBullet this warning won't be shown.

Maybe an obvious question, but did you try to send some test pushes using PushBullet App on your phone, from your PC or in the browser via [https://www.pushbullet.com](https://www.pushbullet.com)?

**Comment by KaezerR** [comment]
I use the SSH protocol to communicate with my raspberry so I always have the answers of the script if necessary.
I do not see any notification or any display of your module when I run the mirror but I can cause its manual appearance in execution thanks to remote module control http: //xxx.xxx.x.xx: 8080 / remote.html

I deactivate the other MMM modules and here are the results: 
```
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-PushBulletNotifications
All module helpers loaded.
Starting server on port 8080 ...
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-PushBulletNotifications
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/fr.fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxom/public/basic.ics - Interval: 300000
Create new calendar fetcher for url: https://outlook.live.com/owaxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1505619/calendar.ics - Interval: 300000
Create new news fetcher for url: https://www.lemonde.fr/rss/une.xml - Interval: 300000
START received
PushBullet connected
(node:2705) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'body' of undefined
(node:2705) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
![capture](https://user-images.githubusercontent.com/41835829/43424308-4a0c3970-944f-11e8-8404-b3da27ab59ac.PNG)


I admit that in the console there are certain groups that I do not find logical, or at least strange.

**Comment by KaezerR** [comment]
> did you try to send some test pushes using PushBullet App on your phone, from your PC or in the browser via https://www.pushbullet.com?

Well seen @basknol , actually between devices the notification from the pushbullet website works, the notifications are displayed on the mirror, but when I receive a message on my phone or any other notifications it does not appear on the mirror, only on the computer pushbullet app. So it's a much less important problem. But still a problem.

**Comment by KaezerR** [comment]
Yes it is @basknol , after many tests, only internal notifications to PushBullet (sent via app) work. No mobile notifications are displayed on the mirror.

**Comment by basknol** [comment]
@SPECTERR We are getting there...I am using the PushBullet App on an iPhone to sent message to my mirror. In PushBullet I have my Magic Mirror, Phone and PC added as a device. Currently I have configured this module so that it will only show notifications that I send to my Mirror and not the notifications all the other devices. Mostly I am using my phone to send notifications to the mirror. But I think with The default configuration it should show pushes sent to all devices. I have not tested this yet with an Android device (or other than iPhone).

What phone are using to test? Can you describe tests you did? I will see if can do some extra testing to check if I can reproduce your problem.

**Comment by KaezerR** [comment]
@basknol My Mirror does not appear in PushBullet in the Device category, it only shows my phone and my computer. I use an Android Smartphone (Samsung Galaxy A5) under Rom Custom. All the notifications that I send from the Android pushbullet platform on my Computer and reverse also appear on the mirror without request (this is not a problem for me), but any notification sent by the Android system (message, or e- mails, ...) only appear on the PushBullet of my computer and not that of Mirror.

**Comment by KaezerR** [comment]
I have tried from other devices, change access token, and check the integrity of the module, nothing has changed.

**Comment by basknol** [comment]
@SPECTERR The MMM-PushBulletNotifications module currently only uses the [RealTime Event Stream](https://docs.pushbullet.com/#realtime-event-stream) with normal pushes (no [ephemerals](https://docs.pushbullet.com/#ephemerals)). It is mentioned in the readme, but probably not completely clear what is means. [Mirrored notifications](https://docs.pushbullet.com/#mirrored-notifications), which I think you are referring to, is currently not implemented in the module. Mirrored notifications are notifications sent from android devices (currently the only source of mirrored notifications) to other devices. Offcourse this is a nice addition to the module, I will see if I can get it implemented :-). 

Concerning the Magic Mirror device in Pushbullet. I have added my Magic Mirror as a device using a curl command, this is described in the readme, see the [Magic Mirror device](https://github.com/basknol/MMM-PushBulletNotifications#magic-mirror-device) section.

**Comment by KaezerR** [comment]
@basknol Indeed it would be a good implementation for other users! For the moment apart from this problem, this version is quite suitable! I fixed the fact that the mirror did not appear in the category device of pushbullet thanks to your indications. Thank you for the help you have given me, and sorry for the many false leads. I wish you a good continuation in the development of your module!

**Comment by basknol** [comment]
Hi @SPECTERR, I don't have any other way of contacting you other then your github username! I have added support for ephemerals (mirrored notifications and SMS) to the MMM-PushBulletNotifications module you might be interested in. Please check the [updated readme](https://github.com/basknol/MMM-PushBulletNotifications). 

<del>Please check the [dev branch](https://github.com/basknol/MMM-PushBulletNotifications/tree/dev) for this version. Maybe you can verify and test if the ephemerals work for you. Feel free to create a new issue if this is not the case.</del>

<del>You can get this branch using: `git clone -b "dev" https://github.com/basknol/MMM-PushBulletNotifications.git`</del>
