### ISSUE TITLE
installation readme

### ISSUE THREAD

**Issue by Rec3ptor** [basknol/MMM-PushBulletNotifications#11]
thanks for the guide, im a noob and got a bit stuck at one point. when you do the curl bit, i needed to add backslashes after each line. 
so this:
curl --header 'Access-Token: <your_access_token_here>'
	 --header 'Content-Type: application/json'
	 --data-binary '{"app_version":1,"manufacturer":"<your_name>","model":"Magic Mirror","nickname":"Magic Mirror","push_token":"","icon":"system"}' 
	 --request POST https://api.pushbullet.com/v2/devices

needed to look like this:
![image](https://user-images.githubusercontent.com/45080921/48581912-0dd12800-e91b-11e8-9fa9-2ba3997812b1.png)

otherwise i got errors for each line such as:
curl access token no url specified

you might want to mention that you can run this command directly from the pi terminal aswell as i had no idea what to do with it :)
lastly, sadly i dont think ios allows you to push notifications at all anymore. maybe im wrong though, i could send messages from the app, but nothing else is pushed. an apple thing i guess.

**Comment by basknol** [comment]
Hi @Rec3ptor,

Thanks for your feedback. 
I have updated the readme:
- Added the backslashes to the curl command.
- Mentioned that the curl command can be executed from the raspberry pi terminal.
- Also mentioned that the creation of a device in Pushbullet is optional and can be used for filtering purposes.

On an iPhone the Pushbullet app can only be used to send normals pushes and display theses messages on the mirror. Mirrored notifications (notifications from other apps like e-mail, WhatsApp etc.) only work on android devices (I have also mentioned this limitation in the readme more clearly).
