### ISSUE TITLE
[Bug] Multiple (WhatsApp) messages get bundled up

### ISSUE THREAD

**Issue by PoltergeistProject** [basknol/MMM-PushBulletNotifications#15]
Hello,

I think I found a new bug; apparently, when multiple Whatsapp messages from the same contact are received (and unread), all of them will get bundled up, in the order they were received, making it practically impossible to read the last ones once enough messages are received.

For testing purposes, I sent two messages on whatsapp in the order: "Message 1" and "Message 2":

![request](https://user-images.githubusercontent.com/36511888/51337663-64302380-1a90-11e9-980e-daf6a6e4f3ac.gif)

As you can see in the attached screencapture, once the second message arrives, the first message will also be displayed in the second notification, before the actual second message.

I'm suggesting a behavior similar to the one from normal pushes and SMS mirrored notification

![request2](https://user-images.githubusercontent.com/36511888/51337827-d30d7c80-1a90-11e9-9236-1c710c5dcb95.gif)

This was not happening until some time ago. I'm not sure what changed; I didn't changed my config and  I reinstalled the module (both master and dev branch)

In case it is usefull this is my config:

```
			module: 'MMM-PushBulletNotifications',
			position: 'top_left',		
			config: {
				accessToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
				numberOfNotifications: 5,
				showPushes: true, 
				showPushesOnLoad: false, 
				showDismissedPushes: false, 
				showMirroredNotifications: true, 
				showMessage: true,
				showIcons: false,
				showDateTime: false,
				maxMsgCharacters: 50,
				maxHeaderCharacters: 50,
				showModuleIfNoNotifications: false,
				playSoundOnNotificationReceived: false,
				debugMode: true,		
				onlyShowLastNotificationFromApplication: false, 
				showIndividualNotifications: true,				
			 }
		},
```
 Thank you

**Comment by basknol** [comment]
Hi @smowk,

Sorry for the delayed response, I was not able to look into this issue earlier.

Unfortunately I was not able to reproduce this behavior. I pulled the latest version from the master branch and I copied your config (except for the AccessToken).
I have also sent two messages using WhatsApp and received them seperately and not bundled up.

See this screencapture.
![mmm-pushbulletnotifications-test](https://user-images.githubusercontent.com/25269915/52371625-5a2d8f00-2a56-11e9-8963-06c41804c7fb.gif)

The MMM-PushBulletNotifications does not concatenate messages. For mirrored notification the following format is used: 

```
<icon(optional)> <application> - <notification title>
<notification message>
```

These value are extracted from the received JSON message from PushBullet, see below.
```
{ type: 'mirror',
  source_device_iden: 'xxx',
  source_user_iden: 'xxx',
  client_version: 289,
  dismissible: true,
  title: 'Bas Knol @ PushBullet',
  body: 'Message 2',
  application_name: 'WhatsApp',
  package_name: 'com.whatsapp',
  notification_id: '1',
  notification_tag: '1549..381@g.us',
  conversation_iden: '{"package_name":"com.whatsapp","tag":"1549...381@g.us","id":1}' 
}
```

I think the MMM-PushBulletNotifications module already receives these messages bundled up. You could verify this, by setting the **debugMode** to true and run the MagicMirror with ```npm start dev``` or ```node serveronly``` and see what the JSON messages from PushBullet looks like.

Please let me know!

**Comment by PoltergeistProject** [comment]
Hi @basknol,

Thank you for your reply, I really appreciate your help.

I've seen you are not using the latest Pushbullet version `client_version: 289` (version: 17.7.20), so I downgraded my Pushbullet to the same version; also, for testing I made a fresh MagicMirror install using only this module (latest master branch) so nothing else can interfere. 

I did the same test I did before, and the results were the same:

```
 { type: 'mirror',
  source_device_iden: 'xxx',
  source_user_iden: 'xxx',
  client_version: 289,
  dismissible: true,
  icon: 'x',
  title: 'Test (2 messages): ​',
  body: 'Message 1\nMessage 2',
  application_name: 'WhatsApp',
  package_name: 'com.whatsapp',
  notification_id: '1',
  notification_tag: '407...211@s.whatsapp.net',
  conversation_iden: '{"package_name":"com.whatsapp","tag":"407...211@s.whatsapp.net","id":1}' }
```
So, I guess you are wright, the module already receives these messages bundled up...
I receive the **second message** as: **'Message 1\nMessage 2'**

You should know that I made the same test with the latest version of the app, with a fresh install of Pushbullet and I also went as far as flashing a sd card (for my raspberry) with an old back up (complete system image) from Nov 2018, when you added the individual notifications functionality on dev branch (yes..I keep a lot of backups) - I know for sure that this was not happening back then.
...and the result was the same, bundled WhatsApp messages

I tought Pushbullet API changed, but you don't seem to have the same issue...

Thank you

**Comment by PoltergeistProject** [comment]
Hello @basknol,

I did a bit more research on this and I think I found the cause of the issue.

I tested on an older phone and, surprisingly, it worked perfectly. That phone was running on Android **6.0.1**.

The phone that shows the previously described behavior runs on Android **8.1.0** and then I found this;

>Starting in Android 7.0 Nougat (API level 24), Android introduced a new way to stack your notifications called bundled notifications.

When you tested and you were not able to reproduce the behavior, were you testing on a older Android version? Do you think this might only be related to Android 7 (and above) devices ?

**Comment by basknol** [comment]
Hello @smowk, 

Thank you for your posts and furthur investigating this issue. 
Yes, I have tested this on an older phone, running an old version of Android.

So, I think you found the reason why the notications are bundled. Do you know if there a possibility to switch off the bundled notifications in Android?

**Comment by PoltergeistProject** [comment]
Hi @basknol,

Thank you for looking into this,

As far as I know, from Android 7 this is how notifications are treated, so I don't think it can be switched off..
