### ISSUE TITLE
can u please help me

### ISSUE THREAD

**Issue by aj6823** [basknol/MMM-PushBulletNotifications#16]
how to call this notification js in standalone html page ?

**Comment by basknol** [comment]
Hi @aj6823, 

Could you elaborate a bit more about what you are trying to achieve?

**Comment by aj6823** [comment]
Can u please help me in calling this js and

**Comment by aj6823** [comment]
Can u please help me in calling this Javascript and css file in html page ..
Cause my final project is smart mirror 
I created the basic smart mirror with the help of js and css that I called in html file and it will display in localhost “var/www/html” so please help me

**Comment by aj6823** [comment]
Screen shot of my smart mirror that will purely developed with the help of html css and JavaScript and am using some API’s
![b3fdae71-f76d-4b0a-bb6b-87133f2bbbd2](https://user-images.githubusercontent.com/42598737/53221609-33936900-3690-11e9-8055-da72b84f1659.jpeg)

**Comment by basknol** [comment]
Hi @aj6823,

Are you using the [MagicMirror ](https://github.com/MichMich/MagicMirror) software?
This module is developed to use with the MagicMirror software. This module uses the syntax and configuration as specified and needed for the MagicMirror software, see [MagicMirror² Module Development Documentation](https://github.com/MichMich/MagicMirror/tree/master/modules).

This module is build to run on node.js and uses other node.js modules to run. You cannot just add this js file to a html page as far as I know. Maybe you can use snippets of the code to achive what you want. 

What are you using to run your solution? Node.js? Webserver?

**Comment by aj6823** [comment]
i am using webserver
but can we run this module only without using magic mirror software just on the webserver ?

**Comment by basknol** [comment]
No, you cannot use this module (as is) without using the Magic Mirror software.

You might want to take a lookt at [pushbullet-js](https://github.com/alexschneider/pushbullet-js).
This is a clientside wrapper for the PushBullet API. You can include it using the script element in your HTML page.
