### ISSUE TITLE
All other modules disappear after a while...

### ISSUE THREAD

**Issue by Cr4z33** [basknol/MMM-PushBulletNotifications#17]
I am using latest version of MagicMirror on a Raspberry Pi 3 B+ running latest Raspbian update.

After a few minutes (there is no specific timing) ALL other modules I am using disappear while MMM-PushBulletNotifications keeps showing.

During the issue all other modules keep working (ie. I can use the Google Assistant module and get vocal answers).

This is how the module  is currently looking like:
`		{
			module: 'MMM-PushBulletNotifications',
			disabled: true,
			header: 'Notifiche',
			position: 'top_left',	// This can be any of the regions.		
			config: {
				// See 'Configuration options' for more information.
				accessToken: "***", //PushBullet API Access Token
				numberOfNotifications: 3,
				filterTargetDeviceName: "",
				showPushesSentToAllDevices: true,
				onlyAllowCommandsFromSourceDevices: [],
				fetchLimitPushBullet: 50,
				showPushes: true,
				showPushesOnLoad: true,
				showDismissedPushes: true,
				showMirroredNotifications: true, 
				onlyShowLastNotificationFromApplication: false,
				showIndividualNotifications: false,
				showSMS: true,
				showMessage: true,
				showIcons: true,
				showDateTime: true,
				localesDateTime: 'nl-NL',
				playSoundOnNotificationReceived: true,
				soundFile: 'modules/MMM-PushBulletNotifications/sounds/new-message.mp3',			
				maxMsgCharacters: 50,
				maxHeaderCharacters: 32,
				showModuleIfNoNotifications: false,
				noNotificationsMessage: "Nessuna nuova notifica",
				debugMode: false,
				}
		}`

**Comment by basknol** [comment]
Hi @Cr4z33,

What exactly is your issue?

In the configuration of the MMM-PushBulletNotification module 'disabled' is set to true.
According to this setting the module should not be shown or is not activated.

Do modules also disappear when you remove the MMM-PushBulletNotifications configuration completely?

Did you test something using commands (pushes prefixed with mm:)?

Maybe you can set debugMode to true to get some logging when you start your Magic Mirror with `npm start dev`

**Comment by Cr4z33** [comment]
Hi @basknol sorry forget the 'disabled= true'.

The issue happens if your module is on.
When it's off everything works correctly.

I already ran MM into dev mode, but I couldn't figure out what's wrong.

I will try again and post here.

**Comment by Cr4z33** [comment]
@basknol it came out it is because of the default update module.

Most of the time it causes MM to crash and that explains the black empty screen then. 

Thanks for your support anyway. ;)
