### ISSUE TITLE
Module Size Request 

### ISSUE THREAD

**Issue by FaiekA** [basknol/MMM-PushBulletNotifications#19]
Apologies probably not posting in the right place - great module works well.
Is there a way increase the module size - running a 42" TV all other modules are fine,
Pushbullet size is to small - is the a way to in crease the size of the text and icon
and where - thanks for any assistance

**Comment by basknol** [comment]
Currently there is no configuration settings to do this. 

If you know how to change the [css ](https://github.com/basknol/MMM-PushBulletNotifications/blob/master/MMM-PushBulletNotifications.css) file you can give it a try yourself.

I will look if I can add some configuration options for this if I have some spare time.

**Comment by FaiekA** [comment]
Hi - Thanks for your response.
That would be great - ill have a look at the Css - not that good yet, still fairly new to this -  but will give it it shot. 
Thanks again

**Comment by basknol** [comment]
Hi @FaiekA,

I have added a branch [css_text_config](https://github.com/basknol/MMM-PushBulletNotifications/tree/css_text_config). 

In this branch I made a version with a couple of CSS configuration options: cssGeneralClass, cssMessageClass, cssDateClass, cssNoNotificationsMessageClass, iconWidth, iconHeight.

Please check the readme in that branch for more information the configuration. Please let me know if you need further assistence or have some feedback. 

Next step is to merge this in the dev and master branche.

**Comment by FaiekA** [comment]
Hi @basknol   -  Thank you - really appreciate your assistance .

**Comment by FaiekA** [comment]
> Hi @basknol - Thank you - really appreciate your assistance .
Just run it and works great - excellent 
Thanks again on a great Module

**Comment by basknol** [comment]
Hi @FaiekA,

Nice! Thanks for letting me know.
