### ISSUE TITLE
How to do it with the cmd ?

### ISSUE THREAD

**Issue by FazCodeFR** [basknol/MMM-PushBulletNotifications#20]
![image](https://user-images.githubusercontent.com/30906528/64920196-d8a09b00-d7b4-11e9-9199-6e0fb42a7d4a.png)
![image](https://user-images.githubusercontent.com/30906528/64920207-ef46f200-d7b4-11e9-87a1-7591f31f24aa.png)

Hello, how to listen with the windows command prompt? Thanks

**Comment by basknol** [comment]
Hi @ABOATDev, 

The curl command in the windows command prompt you are using is to create a device in PushBullet. This device can then be used in the module as a filter, to only show pushes sent to that device.

Maybe you can tell a little more of what you are trying to achieve.

**Comment by FazCodeFR** [comment]
Hello, 
I am trying to receive notifications from IFTTT with the subject "ASSISTANT" directly from the cmd 

![image](https://user-images.githubusercontent.com/30906528/65064692-3f72af80-d981-11e9-8a26-1d1c4b6f43da.png)

Can you help me? Please

**Comment by basknol** [comment]
IFTTT is a channel/subscription in PushBullet, is that correct? I haven't used this functionality before in PushBullet. As far as I can see in the PushBullet [documentation](https://docs.pushbullet.com/#subscription), the messages from the IFTTT are available as pushes with a channel_tag.

Are you using the MMM-PushBulletNotifications module or do you just want to use the PushBullet API?

**Comment by basknol** [comment]
Close issue, inactive.
