### ISSUE TITLE
Is it support notification with Encryption Enabled?

### ISSUE THREAD

**Issue by kexroman** [basknol/MMM-PushBulletNotifications#21]
I tried - all another devices got notifications except  MM. May be Encryption has to be enabled on MM with parameter using  CURL ?

**Comment by basknol** [comment]
Hi @kexroman, 

This module currently does not support encryption. It might be a good enhancement.
What messages are you seeing when setting debugMode to true and running with npm start dev?

**Comment by kexroman** [comment]
Hi, it's looking like that with  **pm2 logs mm**: 

mm-0 [MMM-PushBulletNotifications][Debug] 10:36:17.575 - Ephemeral received
mm-0 { encrypted: true,
mm-0   ciphertext:
mm-0    'MVjS6gw......................EclcAm4wBoF9Fp1WuumN' }
mm-0 nope
mm-0 nope

But it doesn't show any info on MM.

**Comment by basknol** [comment]
Ok, thank you for testing. I will have to take a look in the PushBullet API documentation to see if I can add support for encryption.
