### ISSUE TITLE
[Request] Filter by "o.sender_name"

### ISSUE THREAD

**Issue by moryoav** [basknol/MMM-PushBulletNotifications#24]
When messages are sent to a channel, then the sender name is the name of the channel. So if this module had a way to filter only for a specific sender name, it would be possible to "subscribe" to a channel and only see notifications meant for that channel.

**Comment by basknol** [comment]
@moryoav thanks for the request, will look into it...

**Comment by basknol** [comment]
@moryoav please see the [dev branch](https://github.com/basknol/MMM-PushBulletNotifications/tree/dev). I have added an option filterBySenders. Here you can add the sender or channel name. 

Please let me know if this works for you!
