### ISSUE TITLE
Bar

### ISSUE THREAD

**Issue by MrAirHD** [basknol/MMM-PushBulletNotifications#25]
Hi there,
Is there a possibility to remove the seperation Bar between the Header and the Notifications?
Or can I set it to a fixed size?
I have the News module above it and the bar always changes it´s size to the one of the newsfeed. This is pretty annoying. 

Thanks for any help

**Comment by basknol** [comment]
Hi @MrAirHD, the header and separation bar comes standard with a Magic Mirror module, the content is created in the MMM-PushBulletNotifications module. I don't know if this can be changed easily. Maybe you can try to set the MMM-PushBulletNotifications module to a fixed size using the css configuration options with some custom css. See this [branch ](https://github.com/basknol/MMM-PushBulletNotifications/tree/css_text_config) for the CSS configuration options.
