### ISSUE TITLE
Noob here and need help with custom.css

### ISSUE THREAD

**Issue by Sparkythedog** [basknol/MMM-PushBulletNotifications#26]
Is there anyway to make the revived text message bigger under the name of the text.  This way I can read thew message easier and see if I want to respond.  Thank you in advance.

**Comment by basknol** [comment]
Hi @Sparkythedog, you might want to take a look a this [branch](https://github.com/basknol/MMM-PushBulletNotifications/blob/css_text_config/README.md). In this branch I have added some configuration options to add custom css. Take a look at the configuration options cssGeneralClass, cssMessageClass and cssDateClass.

I still have to merge these additional options to the master branch, but maybe you can try this [branch](https://github.com/basknol/MMM-PushBulletNotifications/blob/css_text_config/README.md) to see if this works for you.
