### ISSUE TITLE
Only show count?

### ISSUE THREAD

**Issue by DoritoMojito** [basknol/MMM-PushBulletNotifications#27]
Is it possible to only show notification count and no message? like so: ![image](https://user-images.githubusercontent.com/55053061/99184101-cb09eb00-2794-11eb-80e0-4194490eadf5.png)

I'd just use it to see if I have a notification at a glance, I don't necessarily want my notifications being displayed. 

(sorry if I've formatted this wrong, first time posting an issue)

**Comment by basknol** [comment]
Hi @DoritoDonthackmeMojito, 

Currently it is not possible to only show a count. 
I will try to add this option for you when I have some spare time.

**Comment by basknol** [comment]
Hi @DoritoDonthackmeMojito, 

I have added some options to the dev branch, please see [here](https://github.com/basknol/MMM-PushBulletNotifications/tree/dev).

You can clone the dev branch by using '-b dev' in your git clone command.

Please try the new option 'showMessageCount' and let me know if this works for you.
If you don't want other info to show up, set these options to false in the config:
- showNameOfSender
- showMessage
- showIcons,
- showDateTime

If you also don't want the module header to show up, just clear the module header from the config.
```
{
     module: "MMM-PushBulletNotifications",
     header: "", //Make the header empty to hide the module header
    ...
    ...
    ...
}
```

**Comment by DoritoMojito** [comment]
I've got it to show a count, however it only seems to appear when I set showDismissedPushes as true and it's also inaccurate 
Pushes as indicated by chrome pushbullet (correct) ![image](https://user-images.githubusercontent.com/55053061/99623560-81651d00-2a80-11eb-8b96-e52506a26323.png)

Pushes as indicated by Mirror pushbullet (incorrect) ![image](https://user-images.githubusercontent.com/55053061/99623605-93df5680-2a80-11eb-85f8-6186c1571909.png)

My pushbullet config entry:
 `		{
			module: 'MMM-PushBulletNotifications',
			header: "",
			position: 'bottom_right',	// This can be any of the regions.		
			config: {
				// See 'Configuration options' for more information.
				accessToken: "**********************************************", //PushBullet API Access Token
				endToEndPassword: null,
				numberOfNotifications: 3,
				filterTargetDeviceName: "",
				filterTargetDeviceNameMode: "simple",
				filterBySenders: [],  
				showPushesSentToAllDevices: true,
				onlyAllowCommandsFromSourceDevices: [],
				fetchLimitPushBullet: 50,
				showPushes: true,
				showPushesOnLoad: true,
				showDismissedPushes: true,
				showMirroredNotifications: true, 
				onlyShowLastNotificationFromApplication: false,
				showIndividualNotifications: false,
				showSMS: true,
				showNameOfSender: false,
				showMessage: false,
				showIcons: false,
				showMessageCount: true,
				showDateTime: false,
				localesDateTime: 'nl-NL',
				playSoundOnNotificationReceived: false,
				soundFile: 'modules/MMM-PushBulletNotifications/sounds/new-message.mp3',			
				maxMsgCharacters: 50,
				maxHeaderCharacters: 32,
				showModuleIfNoNotifications: true,
				noNotificationsMessage: "No new notifications",
				debugMode: false,
			}
		},`

**Comment by basknol** [comment]
@DoritoDonthackmeMojito Thank you for letting me know. I will have to do some additional testing to see why the count is different and why it only shows up when setting showDismissedPushes to true.

**Comment by basknol** [comment]
@DoritoDonthackmeMojito 

I have set the following config options:
- showPushes: true
- showPushesOnLoad: false
- showDismissedPushes: false
- showModuleIfNoNotifications: false

On startup of the Magic Mirror, I don't see any notifications. When I am sending a message from my phone using the PushBullet app, the chrome extension and Magic Mirror receive the notification and the count is shown.
![image](https://user-images.githubusercontent.com/25269915/99724178-868f8f80-2ab3-11eb-9172-fab012181d9d.png)
![image](https://user-images.githubusercontent.com/25269915/99724191-8a231680-2ab3-11eb-9561-257f34c7093c.png)

When I use the chrome extension to sent a push to all devices, this message will show up on the mirror and the count is incremented, but the count for the chrome extension will not increment.
![image](https://user-images.githubusercontent.com/25269915/99724439-e7b76300-2ab3-11eb-8b9d-bf8268d24cbf.png)
![image](https://user-images.githubusercontent.com/25269915/99724509-fd2c8d00-2ab3-11eb-9b35-8a6a38a51f14.png)

When I dismiss the message in the chrome extension, the message will no longer be shown on the Magic Mirror and the count is decremented.
![image](https://user-images.githubusercontent.com/25269915/99724740-5b597000-2ab4-11eb-8f18-6b843978109a.png)
![image](https://user-images.githubusercontent.com/25269915/99724774-6ad8b900-2ab4-11eb-80c7-790fba4de8e1.png)

If this is not working for you, please explain how you are using (or would like to use) PushBullet in combination with Magic Mirror.

**Comment by DoritoMojito** [comment]
I've changed my config settings to be more in line with yours however I needed showModuleIfNoNotifications on so you'd know the module was active at all. I start with no notifications on chrome.
![image](https://user-images.githubusercontent.com/55053061/99753419-4a534200-2b3a-11eb-813b-38b54c5befb2.png)
 And mirror.
![image](https://user-images.githubusercontent.com/55053061/99753430-4e7f5f80-2b3a-11eb-9a13-20cb057d3cdd.png)
Good so far. If I send a test notification to all devices from my phone.
Chrome: 
![image](https://user-images.githubusercontent.com/55053061/99753566-825a8500-2b3a-11eb-8122-bfcee8696833.png)
Mirror:
![image](https://user-images.githubusercontent.com/55053061/99753583-8dadb080-2b3a-11eb-8b90-f13a60d29863.png)
I can confirm that my mirror has internet because my NowPlayingOnSpotify module updates when I change track or pause. The module also doesn't update if I send a push to my phone from chrome. 

Ideally I'd like to use PushBullet on my mirror as a at-a-glance notification check so I can immediately see if I have a notification, if so, how many, and then check my phone. Other people are able to see my mirror hence why I wanted to be able to show only the count.

My config entry for reference:
![image](https://user-images.githubusercontent.com/55053061/99754223-10833b00-2b3c-11eb-9fd9-fcc653758fb0.png)

**Comment by basknol** [comment]
@DoritoDonthackmeMojito 

I have tested this with the same config settings you have sent me. I made a gif, switching between Magic Mirror setup om my windows machine (for testing) and the chrome extension while sending notifications with my phone.
![MM-pushbullet](https://user-images.githubusercontent.com/25269915/99776346-f6803300-2b10-11eb-91c3-076e3d4161fb.gif)

Can you verify that when you start the Magic Mirror that there is a message 'Pushbullet connected'
`[2020-11-20 09:02:06.195] [LOG]    [MMM-PushBulletNotifications][Info] 09:02:06.194 - PushBullet connected`

Maybe you can set the debugMode to true to check if you receive the push, this is logged as a JSON message in the console.

**Comment by DoritoMojito** [comment]
![image](https://user-images.githubusercontent.com/55053061/99794591-7d1f2980-2b7e-11eb-8429-e45f51731448.png)
It appears that it connects, however there is also this
`[2020-11-20 22:15:42.336] [LOG]    [MMM-PushBulletNotifications][Error] 22:15:42.312 - Push stream error: Error: Client network socket disconnected before secure TLS connection was established`
and this 
`[2020-11-20 13:18:43.000] [LOG]    [MMM-PushBulletNotifications][Error] 13:18:42.884 - Error fetching devices. RequestError: Error: Client network socket disconnected before secure TLS connection was established`

I sent multiple pushes from my phone with debugMode enabled and saw no changes in the console.

If it matters at all I'm running the Magic Mirror off of a pi zero w.

**Comment by basknol** [comment]
@DoritoDonthackmeMojito 

Seeing these error message, I think there is no good connection with Pushbullet.

Do you get data from the Pushbullet API if you execute the commands below from the pi zero w (replace <your_access_token_here> with your Pushbullet acess token)?
- `curl --header 'Access-Token: <your_access_token_here>' --data-urlencode active="true" --data-urlencode limit="10" --get https://api.pushbullet.com/v2/pushes`
- `curl --header 'Access-Token: <your_access_token_here>' https://api.pushbullet.com/v2/devices`

A secure connection cannot be made, so we have to figure out what is causing this error.
Are you using a proxy? Can you verify that TLS 1.2 is enabled on your pi zero w?
`openssl ciphers -v | awk '{print $2}' | sort | uniq`

**Comment by DoritoMojito** [comment]
I get valid data running both curls, and when I run the openssl command I get:
![image](https://user-images.githubusercontent.com/55053061/99859996-db332780-2be5-11eb-8027-3e7a27f56886.png)
So I assume it's enabled.

**Comment by DoritoMojito** [comment]
So after getting a message today it seems to have decided to work perfectly, which is curious considering I hadn't done anything after I sent the previous comment.

**Comment by basknol** [comment]
@DoritoDonthackmeMojito Good to hear it works!
