### ISSUE TITLE
Push stream error: Error: certificate has expired

### ISSUE THREAD

**Issue by Cr4z33** [basknol/MMM-PushBulletNotifications#29]
Since a couple of days I noticed that this module wasn't updating the notifications anymore.

Looking at the terminal it now shows
`[2021-10-02 15:43:21.294] [LOG]    [MMM-PushBulletNotifications][Error] 15:43:21.294 - Push stream error: Error: certificate has expired`

What to do to fix it?

**Comment by basknol** [comment]
@Cr4z33 Do you still have this issue? The error looks like a message from the PushBullet API, not directly from the module itself.
Not sure if this will help, but maybe you can try to refresh the PushBullet accesstoken?

**Comment by Cr4z33** [comment]
@basknol sorry forgot to report that updating both MM and your module fixed the issue!

I've not run any sort of updates in my smart mirror since almost 2 years. 😅

Thanks for your support!
