### ISSUE TITLE
notifications doesnt show

### ISSUE THREAD

**Issue by LeyDi1987** [basknol/MMM-PushBulletNotifications#3]
I installed everything, but if i copy/paste the Curl command it gives me an error.
I have a acces token, and my mirror shows the header ' Notifications' but nothing comes up.
How do I set my mirror as a device?

**Comment by basknol** [comment]
Hi @LeyDi1987, 

What error did you get? 

In the readme of MMM-PushBulletNotifications the curl command is shown on multiple lines for readability. If you copy and paste it like that it will probably give some error.

Please try to put the curl command on one line (no enters) when using it in the command prompt:
curl --header 'Access-Token: <your_access_token_here>' --header 'Content-Type: application/json' --data-binary '{"app_version":1,"manufacturer":"<your_name>","model":"Magic Mirror","nickname":"Magic Mirror","push_token":"","icon":"system"}' --request POST https://api.pushbullet.com/v2/devices

Make sure you replace <your_access_token_here> with the PushBullet access token. And <your_name> with a proper value.

Hope this helps to add your mirror as a device to PushBullet.
