### ISSUE TITLE
Push stream error: Error: Unexpected server response: 403

### ISSUE THREAD

**Issue by erfanha** [basknol/MMM-PushBulletNotifications#30]
[12.09.2022 16:27.27.713] [LOG]   [MMM-PushBulletNotifications][Error] 16:27:27.712 - Push stream error: Error: Unexpected server response: 403

whats meaning that error?

**Comment by basknol** [comment]
@erfanha 
It probably means that the access token you have configured in the module configuration is not valid.

The Pushbullet API will retun a 403 Forbidden if the access token is not valid. 
Go to [Pushbullet account settings](https://www.pushbullet.com/#settings/account) to create a (new) access token and set this access token in de module [configuration](https://github.com/basknol/MMM-PushBulletNotifications#configuration-options).
