### ISSUE TITLE
Last notification won't disappear 

### ISSUE THREAD

**Issue by PoltergeistProject** [basknol/MMM-PushBulletNotifications#5]
Great work on this module but apparently the last notification, read or dismissed will not disappear. 
I have tried:
fetchLimitPushBullet: 0,
showPushes: false, 
showPushesOnLoad: false,  
showDismissedPushes: false,
showModuleIfNoNotifications: false,
..but the module allways seems to display one last notification

**Comment by basknol** [comment]
Hi @smowk, 

So you are only using the mirrored notifications and no pushes?
I have done some testing, also with the configuration settings you tried, but I didn't manage to reproduce this problem. Can you describe the steps to reproduce this problem?

The module uses an notification_id from PushBullet to remove the dimissed/read items. Maybe the notification_id is not send by PushBullet in some cases,

If you can reproduce this problem easily, can you set debugMode to true, run the Magic Mirror with `npm start dev` and post the Debug or Error messages that are printed in the console in this issue? This will help me to see if I can fix this.

**Comment by PoltergeistProject** [comment]
Hi @basknol 

Read/dismissed SMS or WhatsApp notifications are disappearing from the mirror;
Pushes are also disappearing from the module...just not the last one

After I carefully read the "Configuration options" descriptions I've seen this:
> showDismissedPushes:  ... If this option is set to false **the latest push is always shown** (is similar to how ephemerals work)

So this is not a bug? Is it working as intended? 
...personally, I can't see the purpose of this.

Just to make things clear, I've sent two pushes (from PushBullet Chrome extension) and dismissed them from my phone; all 4 actions are shown in the debug console:

`[Debug]15:19:43.955 - tickle received: push ` - sent "push 1"
`[Debug]15:19:48.689 - tickle received: push`  - sent "push 2"
`[Debug]15:19:53.252 - tickle received: push`  - dismissed "push 2"
`[Debug]15:19:55.325 - tickle received: push ` - dismissed "push 1" (but was still displayed)


![push](https://user-images.githubusercontent.com/36511888/46608630-26754380-cb0e-11e8-8904-2a4f81a14e17.gif)


Also, this is my config:

```
			config: {
				accessToken: "o.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
				numberOfNotifications: 5,
				showPushes: true,
				showPushesOnLoad: false,  
				showDismissedPushes: false, 
				showMirroredNotifications: true, 
				showMessage: true,
				showIcons: false,
				showDateTime: false,
				maxMsgCharacters: 50,
				maxHeaderCharacters: 45,
				showModuleIfNoNotifications: false,
				playSoundOnNotificationReceived: false,
				debugMode: true,
			 }
```

**Comment by basknol** [comment]
Hi @smowk, 

Thanks for your reply and the supplied debug log and your config!
I managed to reproduce and fix this bug, I have commited changes to the [dev branch](https://github.com/basknol/MMM-PushBulletNotifications/tree/dev). Can you verify if this bug is fixed? Please let me know if this fix is working for you.

During earlier stage of development I probably thought that this was a bug in the PushBullet API and therefore I mentioned in the readme that the last push always is shown when showDismissedPushes was set to false. 

Thanks for reporting this issue.

**Comment by PoltergeistProject** [comment]
Hi @basknol,
The bug is now fixed, Thank you!
