### ISSUE TITLE
[Suggestion/Request] Display more than one SMS/WhatsApp

### ISSUE THREAD

**Issue by PoltergeistProject** [basknol/MMM-PushBulletNotifications#6]
Hi,
Currently, the individual pushes are displayed in individual slots, but SMS and WhatsApp notifications are only using one slot (each), therefore, you can only see the last SMS or WhatsApp message.

The following should clarify the behavior I'm talking about:

First, I'm sending two pushes from the Pushbullet Chrome extension with: "push1" and "push2",
after that, I'm sending 2 SMS messages from the same number: "sms 1" and "sms 2".

Even if the pushes are displayed individually, the SMS messages are stacked, and only the last received message will be displayed; same behavior applies to WhatsApp messages

![suggestion](https://user-images.githubusercontent.com/36511888/47031575-d420cc00-d178-11e8-852a-df680c294cc9.gif)

* I believe that it could be very useful if we could get a config option to display messages individually (SMS / WhatsApp / ephemerals ), but I don't consider this a problem as it is.

What I consider to be a greater inconvenience is the way the previously discussed behavior applies to **conversations on WhatsApp groups**, where only the last message received on a group is displayed, ignoring the number of participants in the conversation

To further clarify how this applies to a group I made the following test:

I made a group named "Test group" and added two participants: "black." and "Phone"; from each account, I sent a message to the group with the text: "1"(from 'black.') and "2"(from 'Phone')

![request](https://user-images.githubusercontent.com/36511888/47032521-3aa6e980-d17b-11e8-9814-3eaae0528ff5.gif)

Initially, I thought that this is a limitation from the API or something like that but I tested with a different MagicMirror module with similar functionality.
The first module is yours, and the second one is an older, deprecated module: https://github.com/maliciousbanjo/PushBulletNotes
* I think the way the second module works (messages from different members are displayed individually) is a lot more useful

Other than this sugestions I'm very impressed with this module; Great work!
Thank you

**Comment by basknol** [comment]
Hi @smowk,

Thank you for your suggestion and the good clarification of it.

I have made some updates, please see the dev branch for the changes. I added two config options 	<code>onlyShowLastNotificationFromApplication</code> and <code>showIndividualNotifications</code>. These options are described in the README, the default value is set to false. 

With both config options set to false, the MMM-PushBulletNotifications module will work similar to the PushBulletNotes module.

If you set <code>onlyShowLastNotificationFromApplication</code>to true the module will work similar to the behavior you described in your post (only the last notification is shown => no change compared to the current situation).

Set <code>showIndividualNotifications</code> to true and <code>onlyShowLastNotificationFromApplication</code> to false if you want to see all WhatsApp messages, not only the last message of a sender.

Another note:
These updates will not change the behavior of how SMS is shown. When SMS mirroring/sync is on and a new SMS is received, PushBullet will first send a dismissal for SMS and the send the new SMS.

Hope this is what you looking for, please let me know.

**Comment by PoltergeistProject** [comment]
Brilliant!! Thank you so much, this module is absolutely great!

**Comment by FaiekA** [comment]
Apologies probably not posting in the right place - great module works well.
Is there a way increase the module size - running a 42" TV all other modules are fine, 
Pushbullet size is to small - is the a way to in crease the size of the text and icon 
and where - thanks for any assistance
