### ISSUE TITLE
Does it work with ios in 2018?

### ISSUE THREAD

**Issue by sajuran123** [basknol/MMM-PushBulletNotifications#8]
Hey I saw it didn't work with ios in 2016, but does it work now? :)

Kind regards

Sajuran

**Comment by basknol** [comment]
Hi @sajuran123,

You can use the PushBullet App on iOS to send messages (pushes) to your Magic Mirror.
But the PushBullet API does not support mirrored notifications on iOS, currently it only has support for Android devices. There is no setting in the PushBullet App on iOS for mirrored notifications.
